package com.statistical.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.statistical.time.bean.BirdayInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BIRDAY_INFO".
*/
public class BirdayInfoDao extends AbstractDao<BirdayInfo, Long> {

    public static final String TABLENAME = "BIRDAY_INFO";

    /**
     * Properties of entity BirdayInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Year = new Property(1, int.class, "year", false, "YEAR");
        public final static Property Max_age = new Property(2, int.class, "max_age", false, "MAX_AGE");
        public final static Property Month = new Property(3, int.class, "month", false, "MONTH");
        public final static Property Day = new Property(4, int.class, "day", false, "DAY");
        public final static Property Hour = new Property(5, int.class, "hour", false, "HOUR");
        public final static Property Minute = new Property(6, int.class, "minute", false, "MINUTE");
        public final static Property Secend = new Property(7, int.class, "secend", false, "SECEND");
        public final static Property IsLunar = new Property(8, boolean.class, "isLunar", false, "IS_LUNAR");
    }


    public BirdayInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BirdayInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BIRDAY_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"YEAR\" INTEGER NOT NULL ," + // 1: year
                "\"MAX_AGE\" INTEGER NOT NULL ," + // 2: max_age
                "\"MONTH\" INTEGER NOT NULL ," + // 3: month
                "\"DAY\" INTEGER NOT NULL ," + // 4: day
                "\"HOUR\" INTEGER NOT NULL ," + // 5: hour
                "\"MINUTE\" INTEGER NOT NULL ," + // 6: minute
                "\"SECEND\" INTEGER NOT NULL ," + // 7: secend
                "\"IS_LUNAR\" INTEGER NOT NULL );"); // 8: isLunar
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BIRDAY_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BirdayInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getYear());
        stmt.bindLong(3, entity.getMax_age());
        stmt.bindLong(4, entity.getMonth());
        stmt.bindLong(5, entity.getDay());
        stmt.bindLong(6, entity.getHour());
        stmt.bindLong(7, entity.getMinute());
        stmt.bindLong(8, entity.getSecend());
        stmt.bindLong(9, entity.getIsLunar() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BirdayInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getYear());
        stmt.bindLong(3, entity.getMax_age());
        stmt.bindLong(4, entity.getMonth());
        stmt.bindLong(5, entity.getDay());
        stmt.bindLong(6, entity.getHour());
        stmt.bindLong(7, entity.getMinute());
        stmt.bindLong(8, entity.getSecend());
        stmt.bindLong(9, entity.getIsLunar() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BirdayInfo readEntity(Cursor cursor, int offset) {
        BirdayInfo entity = new BirdayInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // year
            cursor.getInt(offset + 2), // max_age
            cursor.getInt(offset + 3), // month
            cursor.getInt(offset + 4), // day
            cursor.getInt(offset + 5), // hour
            cursor.getInt(offset + 6), // minute
            cursor.getInt(offset + 7), // secend
            cursor.getShort(offset + 8) != 0 // isLunar
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BirdayInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setYear(cursor.getInt(offset + 1));
        entity.setMax_age(cursor.getInt(offset + 2));
        entity.setMonth(cursor.getInt(offset + 3));
        entity.setDay(cursor.getInt(offset + 4));
        entity.setHour(cursor.getInt(offset + 5));
        entity.setMinute(cursor.getInt(offset + 6));
        entity.setSecend(cursor.getInt(offset + 7));
        entity.setIsLunar(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BirdayInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BirdayInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BirdayInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
