package com.statistical.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.statistical.time.bean.BirdayInfo;
import com.statistical.time.bean.EventInfo;
import com.statistical.time.bean.WishInfo;

import com.statistical.greendao.BirdayInfoDao;
import com.statistical.greendao.EventInfoDao;
import com.statistical.greendao.WishInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig birdayInfoDaoConfig;
    private final DaoConfig eventInfoDaoConfig;
    private final DaoConfig wishInfoDaoConfig;

    private final BirdayInfoDao birdayInfoDao;
    private final EventInfoDao eventInfoDao;
    private final WishInfoDao wishInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        birdayInfoDaoConfig = daoConfigMap.get(BirdayInfoDao.class).clone();
        birdayInfoDaoConfig.initIdentityScope(type);

        eventInfoDaoConfig = daoConfigMap.get(EventInfoDao.class).clone();
        eventInfoDaoConfig.initIdentityScope(type);

        wishInfoDaoConfig = daoConfigMap.get(WishInfoDao.class).clone();
        wishInfoDaoConfig.initIdentityScope(type);

        birdayInfoDao = new BirdayInfoDao(birdayInfoDaoConfig, this);
        eventInfoDao = new EventInfoDao(eventInfoDaoConfig, this);
        wishInfoDao = new WishInfoDao(wishInfoDaoConfig, this);

        registerDao(BirdayInfo.class, birdayInfoDao);
        registerDao(EventInfo.class, eventInfoDao);
        registerDao(WishInfo.class, wishInfoDao);
    }
    
    public void clear() {
        birdayInfoDaoConfig.clearIdentityScope();
        eventInfoDaoConfig.clearIdentityScope();
        wishInfoDaoConfig.clearIdentityScope();
    }

    public BirdayInfoDao getBirdayInfoDao() {
        return birdayInfoDao;
    }

    public EventInfoDao getEventInfoDao() {
        return eventInfoDao;
    }

    public WishInfoDao getWishInfoDao() {
        return wishInfoDao;
    }

}
